// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVCjYjCggrwkjmKYmL3QJpHiKzZz_W3B4',
    appId: '1:602508651790:web:fb0de0bd4f8fc3604afb5f',
    messagingSenderId: '602508651790',
    projectId: 'wavelength-c084c',
    authDomain: 'wavelength-c084c.firebaseapp.com',
    storageBucket: 'wavelength-c084c.firebasestorage.app',
    measurementId: 'G-6LXL6FZ963',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz4wlVm7HZ5BqIcFlFsEQ-ju3gXqR03Ug',
    appId: '1:602508651790:android:240858605ed669a94afb5f',
    messagingSenderId: '602508651790',
    projectId: 'wavelength-c084c',
    storageBucket: 'wavelength-c084c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiaGsOYUfIDUhgiHUjoUnvK-YCbbfAljc',
    appId: '1:602508651790:ios:d7aed7cd3e44dde04afb5f',
    messagingSenderId: '602508651790',
    projectId: 'wavelength-c084c',
    storageBucket: 'wavelength-c084c.firebasestorage.app',
    iosBundleId: 'com.redtea.minddrift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiaGsOYUfIDUhgiHUjoUnvK-YCbbfAljc',
    appId: '1:602508651790:ios:d7aed7cd3e44dde04afb5f',
    messagingSenderId: '602508651790',
    projectId: 'wavelength-c084c',
    storageBucket: 'wavelength-c084c.firebasestorage.app',
    iosBundleId: 'com.redtea.minddrift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVCjYjCggrwkjmKYmL3QJpHiKzZz_W3B4',
    appId: '1:602508651790:web:b3900510c049836b4afb5f',
    messagingSenderId: '602508651790',
    projectId: 'wavelength-c084c',
    authDomain: 'wavelength-c084c.firebaseapp.com',
    storageBucket: 'wavelength-c084c.firebasestorage.app',
    measurementId: 'G-G4Y9WC7P8C',
  );
}
